[문제-1] 길이가 10인 0벡터를 만드세요.

In [2]:
import numpy as np
a = np.zeros(10,dtype='int32')
print(a)

[0 0 0 0 0 0 0 0 0 0]


In [3]:
import numpy as np
a = np.zeros(10,dtype='int32')
print(a)

[0 0 0 0 0 0 0 0 0 0]


[문제-2] 길이가 10이며 다섯번째 원소만 1이고 나머지 원소는 모두 0인 벡터를 만드세요.

In [3]:
import numpy as np
a = np.zeros(10,dtype='int32')
a[4]=1
print(a)

[0 0 0 0 1 0 0 0 0 0]


In [4]:
import numpy as np
a = np.zeros(10,dtype='int32')
a[4]=1
print(a)

[0 0 0 0 1 0 0 0 0 0]


 [문제-3] 10 부터 49까지의 값을 가지는 벡터를 만드세요.

In [5]:
import numpy as np
a = np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [5]:
a = np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


[문제-4] 위 벡터의 순서를 바꾸세요. (역순)

In [6]:
print(a[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [ ]:
a = np.arange(49,9,-1)
print(a)

r = a [::-1]
print(r)

r = np.flip(a)
print(r)

 [문제-5] 0부터 8까지의 값을 가지는 3x3 행렬을 만드세요.

In [8]:
print(np.arange(9).reshape((3,3)))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [7]:
a = np.arange(9).reshape((3,3))
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


[문제-6] 벡터 [1,2,0,0,4,0] 에서 원소의 값이 0이 아닌 원소만 선택한 벡터를 만드세요.

In [13]:
a = np.array([1,2,0,0,4,0],dtype='int32')
b = a[a!=0]
print(b)

[1 2 4]


In [8]:
a = np.array([1,2,0,0,4,0])
print(a[ a != 0])

[1 2 4]


 [문제-7] 3x3 단위 행렬(identity matrix)을 만드세요

In [15]:
import numpy as np
a = np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
a = np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


[문제-8] 난수 원소를 가지는 3x3 행렬을 만드세요

In [18]:
import numpy as np

rng= np.random.default_rng()
a = rng.random((3,3))
print(a)

[[0.2736173  0.13980142 0.26423361]
 [0.35918107 0.74272169 0.118403  ]
 [0.23927202 0.6791951  0.63342607]]


In [16]:
r = np.random.rand(3,3)#rand는 0이상 1미만의 랜덤수
print(r)

[[0.78860378 0.27753791 0.35555986]
 [0.17580933 0.8870712  0.48369909]
 [0.64596397 0.24499923 0.04605837]]


[문제-9] 위에서 만든 난수 행렬에서 최대값/최솟값 원소를 찾으세요.

In [19]:
print(np.max(a))
print(np.min(a))

0.7427216897107904
0.11840300473941068


In [12]:
max = np.max(r)
min = np.min(r)
print(max)
print(min)

0.9376925653532318
0.03834852997019955


[문제-10] 위에서 만든 난수 행렬에서 행 평균, 열 평균을 계산하세요.

In [20]:
print(np.average(a,axis=1))
print(np.average(a,axis=0))

[0.22588411 0.40676859 0.51729773]
[0.29069013 0.52057274 0.33868756]


In [13]:
row_average = np.average(a,axis=1) #방향일떄 axis = 1 은 행을 의미
col_average = np.average(a,axis=0)
print(row_average,col_average)

[0.33333333 0.33333333 0.33333333] [0.33333333 0.33333333 0.33333333]


[문제-11] 5x5짜리 정방행렬의 단위행렬을 생성하시오

In [21]:
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [17]:
a = np.identity(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


 [문제-12] 10~50까지 값 9개를 정수로 발생시켜 출력

In [31]:
a1 = rng.integers(10,51,size=(9),dtype='int32')

In [18]:
a = np.random.randint(10,51,9)
print(a)

[38 39 18 39 45 11 14 44 37]


[문제-13] '문제-12' 배열의 shape을 3x3으로 변환

In [34]:
a1 = a1.reshape((3,3))

In [19]:
a = a.reshape((3,3))
print(a)

[[38 39 18]
 [39 45 11]
 [14 44 37]]


 [문제-14] '문제-13' 배열의 각 행끼리의 합을 구하여 출력

In [35]:
print(a1.sum(axis=1))

[97 86 93]


In [20]:
print(np.sum(a,axis=1))

[95 95 95]


[문제-15] '문제-13' 배열의 각 열 중 최대값 구하여 출력

In [36]:
print(np.max(a1,axis=0))

[35 38 41]


In [21]:
print(np.max(a,axis=0))

[39 45 37]


[문제-16] '문제-13' 배열의 전체 요소의 평균을 구하여 출력

In [37]:
print(np.average(a1))

30.666666666666668


In [22]:
print(np.average(a))

31.666666666666668


 [문제-17] 1~10 사이의 정수를 요소로 하는 2x3 배열 생성

In [38]:
a1 = rng.integers(1,11,size=(2,3))
print(a1)

[[1 5 7]
 [9 9 5]]


In [32]:
b = np.random.randint(1,11,(2,3))
print(b)

[[ 6  7  3]
 [ 6 10  3]]


 [문제-18] 10~20 사이의 정수를 요소로 하는 3x2 배열 생성

In [40]:
a2 = rng.integers(10,21,size=(3,2))
print(a2)

[[18 11]
 [16 14]
 [17 15]]


In [30]:
c = np.random.randint(10,21,(3,2))
print(c)

[[11 19]
 [16 15]
 [20 16]]


 [문제-19] '문제-17'과 '문제-18'의 두 배열의 행렬 곱을 구하여 출력

In [41]:
print(a1@a2)

[[217 186]
 [391 300]]


In [35]:
print(b@c)
print(np.matmul(b,c))
print(np.dot(b,c))
d = b@c

[[238 267]
 [286 312]]
[[238 267]
 [286 312]]
[[238 267]
 [286 312]]


[문제-20] '문제-19' 배열의 전치 행렬을 구하여 출력

In [43]:
print((a1@a2).T)

[[217 391]
 [186 300]]


In [37]:
print(d.T)
print(np.transpose(d))

[[238 286]
 [267 312]]
[[238 286]
 [267 312]]


[문제-21] 로또 번호 생성하기 (1~46 사이의 중복되지 않은 정수 6개 추출)

In [51]:
print(f'로또번호 생성!: {np.random.choice(np.arange(1,47),size=(6),replace=False)}')

로또번호 생성!: [26 23 29  5 11 32]


In [39]:
lotto = np.random.choice(np.arange(1,47),6,replace=False) # 비복원 추출 중복된 값을 만들지 않음
print(lotto)

[45 20 22  9 21  1]
