# [문제] BMI 지수 계산 및 과체중 이상인 BMI 값 확인
- 10명에 대한 키와 몸무게가 들어있는 'height_weight.txt'를 읽어 각 사람별 BMI 지수를 구하고 비만 전단계 이상인 BMI 값 확인하기

<pre>
 BMI 지수 = 몸무게(kg) / 키(M)의 제곱
 체질량지수의 범위 값에 따른 비만도 값 지정
 18.5 미만 ▶ 저체중
 18.5 ~ 22.9 ▶ 정상
 23 ~ 24.9 ▶ 비만 전단계
 25 ~ 29 ▶ 1단계 비만
 30 ~ 34.9 ▶ 2단계 비만
 35이상 ▶ 고도비만
</pre>

In [11]:
import numpy as np
data = np.loadtxt('height_weight.txt', delimiter=',',dtype='float' )
weight = data[1]
height = data[0]
bmi = weight/((height/100)**2)
print( bmi[bmi>=25] )

[27.07018468 25.86122449 25.59220998]


In [19]:
import numpy as np

# 데이터 로딩
data = np.loadtxt('height_weight.txt', delimiter=',', dtype=float)
data [1]
weight = data[1]
height = (data[0]/100)
squared_height = height ** 2
bmi = weight / squared_height
print(bmi[bmi>=25])

[27.07018468 25.86122449 25.59220998]


# [문제] 국가건강검진 혈압혈당 데이터 분석

* '국가건강검진_혈압혈당데이터.csv' 파일 내용을 읽기
    - 성별: 1(남자), 2(여자)
    - 연령그룹: 1(20-24), 2(25-26),...25-74세까지 2살 간격으로 1개 그룹으로 지정, 27(74세 이상)
    - 고혈압 당뇨병 진료여부: 1(고혈압 및 당뇨진료내역 있음), 2(고혈압 진료내역 있음), 3(당뇨 진료내역 있음), 4(고혈압 및 당뇨 진료내역 없음)
    - 정상혈압: 수축기 혈압 120nnHg 미만, 확장기 혈압 80mmHg 미만
    - 공복혈당 수치: 126 mg/dL 이상 -> 당뇨병, 100mg/dL-> 정상
* 전체 레코드 수와 상위 5개 데이터 확인
* 데이터 모양 확인
* 여성과 남성의 데이터 수 확인
* 여성과 남성의 수축기혈압과 확장기혈압의 평균값 확인
* 정상 혈압 남자 및 여자 수 확인
* 당뇨병 질환(공복혈당 수치 126mg/dL 이상)을 가지고 있는 사람들의 평균 체질량지수

In [26]:
import numpy as np

# 데이터 로드
data = np.loadtxt("국가건강검진_혈압혈당데이터.csv", delimiter=",", skiprows=1, encoding = 'cp949')

# # 데이터 모양 확인
# print(data.shape)
# # 전체 데이터 수 확인
# print(data.shape[0])
# #상위 5개 데이터 출력
# print(data[:5])

#하나의 열의 값이 몇가지인지  유니크 , 한 열이 뭐랑 뭐로 나뉘는
gender = np.unique(data[:,0])
print(gender)

# 남성 데이터 수 boolean으로 true면 1 남성이면 true라 1이고 그 값을 다 더하면 데이터 수
print(np.sum(data[:,0]==1)) 
# 남자만 뽑아내는 거
man = (data[data[:,0]==1])
print(man)

# 남성의 수축기 혈압 평균
male_sbp_mean = np.mean(data[data[:,0]==1][:,2])
print(male_sbp_mean)

# 남성의 이완기 혈압 평균
male_dbp_mean = np.mean(data[data[:,0]==1][:,3])
print(male_dbp_mean)

# 정상 혈압 남자 수
normal = np.logical_and(data[:,2]<120, data[:,3]<180)
nbp = data[normal]
print(len(nbp[nbp[:,0]==1]))

# 당뇨병 질환(공복혈당 수치 126mg/dL 이상)을 가지고 있는 사람들의 평균 체질량지수
diabetes = data[data[:,4]>=126]
print(np.mean(diabetes[:,6]))


[1. 2.]
510227
[[  1.    1.  116.  ...  94.    4.   16.6]
 [  1.    1.  100.  ...  79.    4.   22.3]
 [  1.    1.  100.  ...  87.    4.   21.9]
 ...
 [  1.   27.  123.  ... 129.    1.   24.6]
 [  1.   27.  110.  ... 165.    3.   20. ]
 [  1.   27.  130.  ...  91.    1.   23. ]]
124.2799538244742
77.61497725522169
173595
25.168695210981763


# [문제] 시에틀 강수량 데이터 분석
- 'Seattle2014.csv' 파일 내용 읽기
- 강수량('PRCP')이 많은 날 상위 10일 확인
- 1월 강수량만 출력
- 1월에 내린 강수량의 합, 평균강수량 확인
- 1년동안 강수량이 40미만으로 내린 날이 몇일인가?

In [102]:
import numpy as np

# 데이터 로드 dtype 전체다 문자열로 읽는다는 것 숫자 &문자 혼합형 
data = np.loadtxt("Seattle2014.csv", delimiter=",", dtype=object, skiprows=1)


prcp = (data[:, 3].astype('int'))
sorted_data = np.sort(prcp)[::-1][:10]
print(sorted_data)
# 강수량 많은날 상위 10위 날짜도 같이 나오게
prcp_data = (data[:, [2,3]].astype('int'))
print(prcp_data[prcp_data[:,1].argsort()][::-1][:10]) #한 열을 기준으로 정렬하고 두개다 출력

#1월 강수량만 출력
jan = data[:,[2,3]].astype(int)
water=jan[jan[:,0]<20140201]
print(water)

[467 343 333 323 320 277 264 254 221 216]
[[20140305      467]
 [20141128      343]
 [20140503      333]
 [20140308      323]
 [20141022      320]
 [20140316      277]
 [20140216      264]
 [20141030      254]
 [20140328      221]
 [20140129      216]]
[[20140101        0]
 [20140102       41]
 [20140103       15]
 [20140104        0]
 [20140105        0]
 [20140106        3]
 [20140107      122]
 [20140108       97]
 [20140109       58]
 [20140110       43]
 [20140111      213]
 [20140112       15]
 [20140113        0]
 [20140114        0]
 [20140115        0]
 [20140116        0]
 [20140117        0]
 [20140118        0]
 [20140119        0]
 [20140120        0]
 [20140121        0]
 [20140122        5]
 [20140123        0]
 [20140124        0]
 [20140125        0]
 [20140126        0]
 [20140127        0]
 [20140128       89]
 [20140129      216]
 [20140130        0]
 [20140131       23]]


In [109]:
prcp_data = data[:,[2,3]]
prcp_data = np.array([[date[4:6],prcp]for date, prcp in prcp_data])
jan = prcp_data[prcp_data[:,0]=='01'][:,1].astype(int)
print(jan)

water = np.sum(jan)
print(water)
wateravg = np.mean(jan)
print(wateravg)

prcp_1 = data[:,3].astype(int)
under_40 = prcp_1[prcp_1 < 40]
print(len(under_40))

[  0  41  15   0   0   3 122  97  58  43 213  15   0   0   0   0   0   0
   0   0   0   5   0   0   0   0   0  89 216   0  23]
940
30.322580645161292
277


# [문제] 영화 평점 분석
- 'ratings.dat' 파일 내용 읽기 (데이터 형식: user_id::item_id::rating::timestamp)
- 상위 10개 데이터 출력하기
- 데이터 정보 확인(크기, 차원)
- 전체 데이터 평점 구하기
- 사용자 아이디 1인 데이터 출력하기
- 사용자 아이디 1인 사람의 평점 평균 구하기
- 각 사용자별 평점 구하기 (사용자 ID 수집: ID컬럼에 대한 np.unique() 함수 적용)
- 각 사용자별 평균 평점이 4점 이상인 사용자 및 인원수 구하기

In [141]:
import numpy as np

# 데이터 정보 확인(크기, 차원)
data = np.loadtxt('ratings.dat', delimiter=':', dtype=np.int64)
print(data[:10])
print(data.shape)
print(data.ndim)

# 전체 데이터 평균 평점 구하기
print('평균평점',np.mean(data[:,2]))

# 사용자 아이디 1인데이터 출력하기
only_id = data[:, 0]==1
print(data[only_id])

# 사용자 아이디 1인 사람의 평균 평점구하기a
mean =np.mean(data[only_id][:,2])
print(mean)

# 각 사용자별 평균 평점 구하기
ids = np.unique(data[:, 0])
user_avg_rating = [[id, np.mean(data[data[:, 0] == id][:, 2].astype(float))] for id in ids]

for id, rating in user_avg_rating[:10]:
    print(id, rating)

[[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 [        1      3408         4 978300275]
 [        1      2355         5 978824291]
 [        1      1197         3 978302268]
 [        1      1287         5 978302039]
 [        1      2804         5 978300719]
 [        1       594         4 978302268]
 [        1       919         4 978301368]]
(1000209, 4)
2
평균평점 3.581564453029317
[[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 [        1      3408         4 978300275]
 [        1      2355         5 978824291]
 [        1      1197         3 978302268]
 [        1      1287         5 978302039]
 [        1      2804         5 978300719]
 [        1       594         4 978302268]
 [        1       919         4 978301368]
 [        1       595         5 978824268]
 [        1       938         4 978301752]
 [        1    

In [142]:
user_avg_rating = np.array(user_avg_rating)
print(np.sum(user_avg_rating[:,1]>=4))

1544
